---
title: "Homework assignment 1. Programación y modelación financiera (PMF)"
author: "XXXX XXXX, Lara Weitgasser A01759114"
date: "8/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyquant)
library(ggplot2)
library(quantmod)
library(finreportr)
library(tibble)
library(tbl2xts)
library(dplyr)
library(lazyeval)
```

## R Markdown



```{r cars}
Stock_AFGN <- tq_get(c("AMZN","FB","GOOG","NFLX"))%>%
     group_by(symbol) %>%
     ggplot(aes(x = date, y = adjusted, color = symbol)) +
     geom_line(size = 1) +
     coord_x_date(xlim = c("2016-12-30","2021-07-31"))+
     labs(title = "Daily stock prices - 2016-12-30 to 2021-07-31",
          x = "", y = "Adjusted prices", color = "") +
     scale_y_continuous(labels = scales::dollar) +
     theme_tq() + scale_color_tq()
Stock_AFGN

```


```{r}
Stock_AFGN <- tq_get(c("AMZN","FB","GOOG","NFLX"))%>%
     group_by(symbol) %>%
     ggplot(aes(x = date, y = adjusted, color = symbol)) +
     geom_line(size = 1) +
     coord_x_date(xlim = c("2016-12-30","2021-07-31"))+
     labs(title = "Daily stock prices - 2016-12-30 to 2021-07-31",
          x = "", y = "Adjusted prices", color = "") +
        facet_wrap(~ symbol, ncol = 2, scales = "free_y") +
     scale_y_continuous(labels = scales::dollar) +
     theme_tq() + scale_color_tq()
Stock_AFGN
```


```{r}
Stock_AFGN_annual_returns <- tq_get(c("AMZN","FB","GOOG","NFLX"))%>%
     group_by(symbol) %>%
        filter(date>"2016-12-30")%>%
        tq_transmute(select = adjusted,
        mutate_fun = periodReturn,
        period = "yearly",
        type = "arithmetic")

Stock_AFGN_annual_returns
```


```{r}
Stock_AFGN_annual_returns %>%
ggplot(aes(x = date-365, y = yearly.returns, fill = symbol)) +
geom_col() +
geom_hline(yintercept = 0, color = palette_light()[[1]]) +
scale_y_continuous(labels = scales::percent) +
labs(title = "FANG: Annual Returns",
y = "Annual Returns", x = "") +
facet_wrap(~ symbol, ncol = 2, scales = "free_y") +
theme_tq() + scale_fill_tq()
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
